// src/attributeLists.js
export const cyberpunkAttributes = {
  "Skin tone (12):": "12",
  "Skin type (5):": "5",
  "Hairstyle (51):": "51",
  "Hair color (35):": "35",
  "Eyes (21):": "21",
  "Eye color (9):": "9",
  "Eyebrows (13):": "13",
  "Nose (21):": "21",
  "Mouth (21):": "21",
  "Jaw (21):": "21",
  "Ears (21):": "21",
  "Beard (13):": "13",
  "Beard style (3/7):": "3-7",
  // "Cyberware (10):": "10",
  "Facial scars (14):": "14",
  "Facial tatoos (16):": "16",
  "Blemishes (4):": "4",
  "Blemisher color (6):": "6",
  "Body tattoos (8):": "8",
  "Body scars (3):": "3"
};

export const avowedAttributes = {
  "Body (24)": "24",
  "Skin Color (24)": "24",
  "Face (14)": "14",
  "Godlike (14)": "14",
  "Godlike hair (4)": "4",
  "Hair (50)": "50",
  "Hair root (18)": "18",
  "Beard (18)": "18",
  "Eyes x 5": "-5-5",
  "Eye color (10)": "10",
  "Brows x 5": "11",
  "Nose x 5": "11",
  "Face x 9": "11",
  "Mouth x 4": "11",
  "Ears x 3": "11",
  "Completion (10)": "9",
  "Amount (10)": "0-10",
  "Spread (10)": "0-10",
  "Completion color (8)": "8",
  "Background (5)": "5",
  "Voice (2)": "2"
};

// dragonageAttributes.js
export const dragonageAttributes = [
  { type: "header", label: "Head" },
  { type: "small-header", label: "Head Shape" },
  { name: "Head top", max: 30 },
  { name: "Head bottom left", max: 30 },
  { name: "Head bottom-right", max: 30 },

  { type: "header", label: "Head" },
  { type: "small-header", label: "Complexion" },
  { name: "Skin Hue", options: ["Warm", "Neutral", "Cool"] },
  { name: "Skin Tone", max: 16 },
  { name: "Melanin", min: 60, max: 100, percent: true }, // 0, 5, 10, ..., 100
  { name: "Complexion", max: 42 },

  { type: "header", label: "Head" },
  { name: "Head Width", min: -100, max: 100, step: 5, percent: true },
  { name: "Flatten", max: 100, step: 5, percent: true },
  { name: "Width", min: -100, max: 100, step: 5, percent: true },
  { name: "Depth", min: -100, max: 100, step: 5, percent: true },

  { type: "small-header", label: "Brow" },
  { name: "Spacing", min: -100, max: 100, step: 5, percent: true },
  { name: "Width", min: -100, max: 100, step: 5, percent: true },
  { name: "Height", min: -100, max: 100, step: 5, percent: true },
  { name: "Inner Position", min: -100, max: 100, step: 5, percent: true },
  { name: "Outer Position", min: -100, max: 100, step: 5, percent: true },
  { name: "Depth", min: -100, max: 100, step: 5, percent: true },

  { type: "header", label: "Head" },
  { type: "small-header", label: "Cheeks" },
  { name: "Depth", min: -100, max: 100, step: 5, percent: true },
  { name: "Height", min: -100, max: 100, step: 5, percent: true },
  { name: "Width", min: -100, max: 100, step: 5, percent: true },
  { name: "Gauntness", min: -100, max: 100, step: 5, percent: true },
  { name: "Jowls", min: -100, max: 100, step: 5, percent: true },

  { type: "small-header", label: "Jaw" },
  { name: "Overbite", min: -100, max: 100, step: 5, percent: true },
  { name: "Height", min: -100, max: 100, step: 5, percent: true },
  { name: "Width", min: -100, max: 100, step: 5, percent: true },

  { type: "small-header", label: "Jaw bone angle" },
  { name: "Depth", min: -100, max: 100, step: 5, percent: true },
  { name: "Position", min: -100, max: 100, step: 5, percent: true },
  { name: "Width", min: -100, max: 100, step: 5, percent: true },

  { type: "header", label: "Head" },
  { type: "small-header", label: "Chin" },
  { name: "Chin Bump", max: 100, step: 5, percent: true },
  { name: "Width", min: -100, max: 100, step: 5, percent: true },
  { name: "Depth", min: -100, max: 100, step: 5, percent: true },
  { name: "Heigth", min: -100, max: 100, step: 5, percent: true },
  { name: "Double Chin", min: -100, max: 100, step: 5, percent: true },

  { type: "header", label: "Head" },
  { type: "small-header", label: "Larynx" },
  { name: "Depth", min: -100, max: 100, step: 5, percent: true },
  { name: "Height", min: -100, max: 100, step: 5, percent: true },
  { name: "Width", min: -100, max: 100, step: 5, percent: true },

  { type: "header", label: "Head" },
  { type: "small-header", label: "Scalp" },
  { name: "Flatten top", max: 100, step: 5, percent: true },
  { name: "Flatten Back", max: 100, step: 5, percent: true },
  { name: "Flatten Both Sides", max: 100, step: 5, percent: true },
  { name: "Flatten Left Sides", max: 100, step: 5, percent: true },
  { name: "Flatten Right Sides", max: 100, step: 5, percent: true },
  { name: "Width", min: -100, max: 100, step: 5, percent: true },
  { name: "Height", min: -100, max: 100, step: 5, percent: true },
  { name: "Profile", min: -100, max: 100, step: 5, percent: true },
  { name: "Scale", min: -100, max: 100, step: 5, percent: true },

  { type: "header", label: "Body" },
  { type: "small-header", label: "Body proportions" },
  { name: "Height", min: -100, max: 100, step: 5, percent: true },
  { name: "Shoulder Width", min: -100, max: 100, step: 5, percent: true },
  { name: "Chest Size", min: -100, max: 100, step: 5, percent: true },
  { name: "Waist Width", min: -100, max: 100, step: 5, percent: true },
  { name: "Hip Width", min: -100, max: 100, step: 5, percent: true },
  { name: "Glute Size", min: -100, max: 100, step: 5, percent: true },
  { name: "Bulge Size", min: -100, max: 100, step: 5, percent: true },

  { type: "header", label: "Eyes and Eybrows" },
  { type: "small-header", label: "Eye Shape" },
  { name: "Spacing", min: -100, max: 100, step: 5, percent: true },
  { name: "Up / Down", min: -100, max: 100, step: 5, percent: true },
  { name: "Left Up / Down", min: -100, max: 100, step: 5, percent: true },
  { name: "Right Up / Down", min: -100, max: 100, step: 5, percent: true },
  { name: "Depth", max: 100, step: 5, percent: true },
  { name: "Tilt", min: -100, max: 100, step: 5, percent: true },

  { type: "small-header", label: "Eye Lids" },
  { name: "Vertical Distance", min: -100, max: 100, step: 5, percent: true },
  { name: "Left Vertical Distance", max: 100, step: 5, percent: true },
  { name: "Right Vertical Distance", max: 100, step: 5, percent: true },
  { name: "Hooded", max: 100, step: 5, percent: true },

  { type: "small-header", label: "Eye Color" },
  { name: "Middle Iris Color", max: 29 },
  { name: "Saturation", max: 100, percent: true },
  { name: "Brightness", max: 100, percent: true },

  { type: "small-header", label: "Eye Color" },
  { name: "Inner Iris Color", max: 29 },
  { name: "Saturation", max: 100, percent: true },
  { name: "Brightness", max: 100, percent: true },

  { type: "small-header", label: "Eye Color" },
  { name: "Outer Iris Color", max: 29 },
  { name: "Saturation", max: 100, percent: true },
  { name: "Brightness", max: 100, percent: true },

  { type: "header", label: "Eyes and Eybrows" },
  { type: "small-header", label: "Eyebrows" },
  { name: "Shape", max: 51 },

  { type: "small-header", label: "Eyelashes" },
  { name: "Shape", max: 47 },

  { type: "small-header", label: "Mascara" },
  { name: "Intensity", max: 100, percent: true },

  { type: "header", label: "Nose" },
  { type: "small-header", label: "Nose Shape" },
  { name: "Nose Shape", max: 9, percent: true },
  { name: "Depth", min: -100, max: 100, step: 5, percent: true },
  { name: "Height", min: -100, max: 100, step: 5, percent: true },
  { name: "Size", min: -100, max: 100, step: 5, percent: true },
  { name: "Crookedness", min: -100, max: 100, step: 5, percent: true },

  { type: "small-header", label: "Nose Bone" },
  { name: "Depth", min: -100, max: 100, step: 5, percent: true },
  { name: "Height", min: -100, max: 100, step: 5, percent: true },
  { name: "Width", min: -100, max: 100, step: 5, percent: true },

  { type: "small-header", label: "Nose Bridge" },
  { name: "Vertical Position", min: -100, max: 100, step: 5, percent: true },
  { name: "Horizontal Position", min: -100, max: 100, step: 5, percent: true },
  { name: "Width", min: -100, max: 100, step: 5, percent: true },
  { name: "Depth", min: -100, max: 100, step: 5, percent: true },

  { type: "small-header", label: "Nose Tip" },
  { name: "Depth", min: -100, max: 100, step: 5, percent: true },
  { name: "Up / Down", min: -100, max: 100, step: 5, percent: true },
  { name: "Left / Right", min: -100, max: 100, step: 5, percent: true },
  { name: "Width", min: -100, max: 100, step: 5, percent: true },
  { name: "Rotation", min: -100, max: 100, step: 5, percent: true },

  { type: "small-header", label: "Nostrils" },
  { name: "Size", min: -100, max: 100, step: 5, percent: true },
  { name: "Width", min: -100, max: 100, step: 5, percent: true },
  { name: "Depth", min: -100, max: 100, step: 5, percent: true },

  { type: "header", label: "Mouth" },
  { type: "small-header", label: "Mouth Shape and Position" },
  { name: "Width", min: -100, max: 100, step: 5, percent: true },
  { name: "Depth", min: -100, max: 100, step: 5, percent: true },
  { name: "Position", min: -100, max: 100, step: 5, percent: true },
  { name: "Size", min: -100, max: 100, step: 5, percent: true },
  { name: "Lip Thickness", min: -100, max: 100, step: 5, percent: true },
  { name: "Upper Lip Size", min: -100, max: 100, step: 5, percent: true },
  { name: "Lower Lip Size", min: -100, max: 100, step: 5, percent: true },
  { name: "Mouth Corner Position", min: -100, max: 100, step: 5, percent: true },

  { type: "header", label: "Ears" },
  { type: "small-header", label: "Ear Shape and Position" },
  { name: "Ear Shape", max: 9 },
  { name: "Size", min: -100, max: 100, step: 5, percent: true },
  { name: "Earlobe Size", max: 100, step: 5, percent: true },
  { name: "Left Cauliflower Ear", max: 100, step: 5, percent: true },
  { name: "Right Cauliflower Ear", max: 100, step: 5, percent: true },
  { name: "Depth", min: -100, max: 100, step: 5, percent: true },
  { name: "Rotation", min: -100, max: 100, step: 5, percent: true },
  { name: "Height", min: -100, max: 100, step: 5, percent: true },
  { name: "Position", min: -100, max: 100, step: 5, percent: true },

  { type: "header", label: "Hair" },
  { type: "small-header", label: "Hairstyle" },
  { name: "White Male", options: [1, 2, 3, 4, 6, 8, 11, 15, 16, 17, 19, 21, 22, 23, 24, 26, 27, 32, 35, 37, 39, 40, 41, 43, 45, 46, 47, 51, 53, 54, 57, 59, 60, 61, 62, 63, 64, 68, 70, 72, 73, 75, 76, 77, 81, 85, 86] },
  { name: "Black Male", options: [1, 2, 3, 4, 7, 12, 17, 18, 19, 20, 24, 33, 35, 38, 44, 50, 52, 55, 56, 58, 63, 65, 66, 67, 70, 71, 72, 73, 74, 76, 78, 79, 83, 84, 88] },
  { name: "White Female", options: [6, 8, 10, 13, 15, 21, 22, 25, 26, 27, 28, 31, 34, 36, 37, 39, 40, 41, 42, 43, 46, 47, 48, 50, 51, 53, 54, 57, 60, 61, 63, 64, 68, 69, 78, 80, 81, 88] },
  { name: "Black Female", options: [5, 12, 17, 18, 20, 24, 30, 33, 35, 38, 39, 42, 44, 49, 50, 52, 55, 56, 58, 63, 65, 66, 67, 70, 73, 74, 78, 79, 83, 84, 88] },

  { type: "small-header", label: "Facial Hair" },
  { name: "White Facial Hair", options: [1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 20, 22, 23, 25, 26, 27, 28, 29, 30, 32, 36, 37, 40, 41, 42, 43, 44] },
  { name: "Black Facial Hair", options: [1, 2, 3, 13, 14, 15, 25, 26, 31, 33, 34, 35, 36, 37, 40, 41, 42, 43, 44] },

  { type: "small-header", label: "Hair color" },
  { name: "Hair Color", max: 37 },
  { name: "Saturation", max: 100, percent: true },
  { name: "Brightness", max: 100, percent: true },

  { type: "header", label: "Tattoos, scars, and paint" },
  { type: "small-header", label: "Body tattoos" },
  { name: "Tattoo Design", max: 22 },

  { type: "small-header", label: "Facial Scars" },
  { name: "Scar Shape", max: 34 },

  { type: "small-header", label: "Body Scars" },
  { name: "Scar Shape", max: 27 },

  // { type: "header", label: "Eye Makeup" },
  // { name: "Style", max: 36 },

  // { type: "small-header", label: "Eye Shadow" },
  // { name: "Tattoo Design", max: 14 },

  // { type: "small-header", label: "Eye Shadow" },
  // { name: "Tattoo Design", max: 11 },

  { type: "small-header", label: "Voice" },
  { name: "Voice type", max: 2 },
  { name: "Voice pitch", options: ["Medium", "Low"] },

  { type: "small-header", label: "Factions" },
  { name: "Faction", options: ["Antivan Crows", "Grey Wardens", "Lords of Fortune", "Shadow Dragons", "The Mourn Watch", "Veil Jumpers"] },

];

